name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test_windows_libuv:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build hammer_test
        run: |
          vcpkg install libuv:x64-windows
          cl /I C:\vcpkg\installed\x64-windows\include /MT /W3 /D WIN32_LEAN_AND_MEAN /D LIBUS_USE_LIBUV /D LIBUS_NO_SSL /std:c11 /I src examples/hammer_test.c src/*.c src/eventing/*.c src/crypto/*.c /EHsc /Ox C:\vcpkg\installed\x64-windows\lib\uv.lib advapi32.lib
          cl /I C:\vcpkg\installed\x64-windows\include /MT /W3 /D WIN32_LEAN_AND_MEAN /D LIBUS_USE_LIBUV /D LIBUS_NO_SSL /std:c11 /I src examples/hammer_test_unix.c src/*.c src/eventing/*.c src/crypto/*.c /EHsc /Ox C:\vcpkg\installed\x64-windows\lib\uv.lib advapi32.lib
          cp C:\vcpkg\installed\x64-windows\bin\uv.dll uv.dll
          dir
          ./hammer_test.exe
          ./hammer_test_unix.exe
  
  test_macos_libuv:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libuv
      run: brew install libuv
    - name: build examples
      run: WITH_LIBUV=1 WITH_ASAN=1 make examples
    - name: run test
      run: ./hammer_test && ./hammer_test_unix

  test_macos_kqueue:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build examples
      run: WITH_ASAN=1 make examples
    - name: run test
      run: ./hammer_test && ./hammer_test_unix

  test_linux_libuv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libuv
      run: sudo apt install -y libuv1-dev
    - name: build examples
      run: WITH_LIBUV=1 WITH_ASAN=1 make examples
    - name: run test
      run: ./hammer_test && ./hammer_test_unix

  test_linux_epoll:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build examples
      run: WITH_ASAN=1 make examples
    - name: run test
      run: ./hammer_test && ./hammer_test_unix
